version: 0.2

phases:
  build:
    commands:
      - echo Build started
      - python --version
  post_build:
    commands:
      - echo Build completed
      - pwd
      - ls -al
      - zip raq-alexa-lambda.zip lambda_function.py
artifacts:
  files:
    - raq-alexa-lambda.zip
