version: 0.2

phases:
  build:
    commands:
      - echo Build started
      - python --version
  post_build:
    commands:
      - echo Build completed
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'
