version: 0.0

phases:

  install:
    commands:
      - pip install pymysql
    finally:
      - echo "pymysql installed"
  build:
    commands:

  post_build:
    commands:


    finally:

artifacts:
  files:
    - '**/*'
  name: $PROJECT_NAME-$GIT_DESCRIBE
  base-directory: target/dist/
  discard-paths: no
