version: 0.2

phases:
  install:
    commands:
      - echo START installing PyMySQL
      - pip install pymysql -t .
      - echo FINISHED installing PyMySQL

      - echo START installing AWS CLI
      - pip install awscli
      - echo FINISHED installing AWS CLI
    finally:
      - python --version
      - aws --version
  build:
    commands:
      - echo List some Infos
      - pwd
      - ls -al
      - aws lambda list-functions
      - echo start zipping
      - zip -r raq-alexa-lambda.zip lambda_function.py pymy* PyMy*
      - echo start deploy
      - aws lambda update-function-code --function-name alexaFunctionRAQ --zip-file fileb://raq-alexa-lambda.zip \
      - echo update done
  post_build:
    commands:
      - rm buil*
      - rm *.zip
artifacts:
  files:
    - '**/*'
    #- raq-alexa-lambda.zip
