version: 0.2

phases:
  install:
    commands:
      - echo START installing PyMySQL
      - pip install pymysql -t .
      - echo FINISHED installing PyMySQL
      - echo START installing AWS CLI
      - pip install awscli
      - echo FINISHED installing AWS CLI
    finally:
      - python --version
      - aws --version
  build:
    commands:
      - echo try to zip and pseudo deploy
      - ls -al
      - zip -r raq-alexa-lambda.zip lambda_function.py pymy* PyMy*
      - pwd
      - aws lambda update-function-code --function-name arn:aws:lambda:us-east-1:397480882494:function:alexaFunctionRAQ --zip-file fileb://raq-alexa-lambda.zip
    finally:
      - echo function update done
  post_build:
    commands:
      - echo clean up
      - rm buil*
      - rm *.zip
      - pwd
artifacts:
  files:
    - '**/*'
