version: 0.0

phases:

  install:
    commands:
      - pip install pymsql
    finally:
      - echo "pymsql installed"
  build:
    commands:

  post_build:
    commands:
      - find target/
    finally:
      - printenv
artifacts:
  files:
    - '**/*'
  name: $PROJECT_NAME-$GIT_DESCRIBE
  base-directory: target/dist/
  discard-paths: no
