version: 0.2

phases:
  build:
    commands:
      - echo Build started
      - python --version
      - echo trying to install PyMySql and AWS CLI
      - pip install pymysql -t .
      - echo PyMySql installed
      - pip install awscli
      - echo AWS CLI installed
      - aws --version
  post_build:
    commands:
      - echo Build completed
      - pwd
      - zip -r raq-alexa-lambda.zip lambda_function.py pymy* PyMy*
      - ls -al
      # - aws lambda update-function-code --function-name "alexaFunctionRAQ" --zip-file "raq-alexa-lambda.zip"
artifacts:
  files:
    - raq-alexa-lambda.zip
